# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  pull_request:
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@main

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
